AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Listen to notifications on an SNS topic to trigger a build in CodeBuild

Parameters:
  EssentialsStackName:
    Type: String
    Default: essentials

Resources:
  TriggerBuildFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Listen to notifications on an SNS topic to trigger a build in CodeBuild
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 60
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'codebuild:StartBuild'
              Resource: '*'
      Events:
        TriggerBuildMessage:
          Type: SNS
          Properties:
            Topic: !ImportValue
                               'Fn::Sub': '${EssentialsStackName}:TriggerBuildsTopicARN'
